name: Run The Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Unit Testing
        run: python manage.py test
        working-directory: ./ciphers_project

      - name: Build and push the image
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io --username prithvia28 --password-stdin
          docker build -t ghcr.io/prithvia28/ciphers-service:latest --file Dockerfile .
          docker push ghcr.io/prithvia28/ciphers-service:latest
